#.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## XYZ Amplify Services
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
#.title~

name: xyz_amplify_services
publish_to: none
version: 0.1.0

## -----------------------------------------------------------------------------
 
environment:

  sdk: '>= 3.0.0 < 4.0.0'
  flutter: '>= 3.0.0 < 4.0.0'

## -----------------------------------------------------------------------------

dependencies:

  flutter:
    sdk: flutter

  amplify_flutter: ^1.6.0
  amplify_auth_cognito: ^1.6.0

  xyz_service_brokers:
    git:
      url: https://github.com/robmllze/xyz_services.git
      path: xyz_service_brokers
  

## -----------------------------------------------------------------------------

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints:

## -----------------------------------------------------------------------------

flutter: