#.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## XYZ Firebase Services
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
#.title~

name: xyz_firebase_services
publish_to: none
version: 0.1.0

## -----------------------------------------------------------------------------

environment:

  sdk: '>= 3.0.0 < 4.0.0'
  flutter: '>= 3.0.0 < 4.0.0'

## -----------------------------------------------------------------------------

dependencies:

  flutter:
    sdk: flutter
  cloud_firestore:
  firebase_auth:

  xyz_service_brokers:
    git:
      url: https://github.com/robmllze/xyz_services.git
      path: xyz_service_brokers

## -----------------------------------------------------------------------------

dev_dependencies:
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

## -----------------------------------------------------------------------------

flutter: