#.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## XYZ Service Brokers
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
#.title~

name: xyz_service_brokers
publish_to: none
version: 0.1.0

## -----------------------------------------------------------------------------

environment:

  sdk: '>= 3.0.0 < 4.0.0'
  flutter: '>= 3.0.0 < 4.0.0'

## -----------------------------------------------------------------------------

dependencies:

  flutter:
    sdk: flutter
  meta:
  xyz_utils:
    git:
      url: https://github.com/robmllze/xyz_utils.git
      ref: master
  xyz_pod:
    git:
      url: https://github.com/robmllze/xyz_pod.git
      ref: master

## -----------------------------------------------------------------------------

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints:

## -----------------------------------------------------------------------------

flutter: